version: '2'

networks:
  simplesaml-network:
    driver: bridge

services:

  simplesaml:
    networks:
      simplesaml-network:
    image: simplesamlphp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplesaml
    environment:
      - TERM=xterm
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      #- ./simplesamlphp:/var/simplesamlphp
      - ./config:/var/simplesamlphp/config
      - ./metadata:/var/simplesamlphp/metadata
      - ./cert:/var/simplesamlphp/cert

